ctrl_interface=/var/run/wpa_supplicant
update_config=1
ap_scan=1

# Set the correct ISO country code for your deployment.
country=KR

network={
  ssid="skyiptime118D"
  psk="skylife18d"
  key_mgmt=WPA-PSK
}
